### ISSUE TITLE
pylode IRI when copying

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [BrickSchema/brick-website#102]
**Describe the bug**
When copying the IRI of a resource the pylode IRI is copied, e.g.

> http://www.linked.data.gov.au/def/pylode/brick.html#zone_air_temperature_setpoint

instead of 

> https://brickschema.org/ontology/1.1/classes/Zone_Air_Temperature_Setpoint/

**To Reproduce**
1. Go to 'https://brickschema.org/ontology/1.1/classes/Zone_Air_Temperature_Setpoint/'
2. Copy link in IRI'

**Expected behavior**
The copied content should be
> https://brickschema.org/ontology/1.1/classes/Zone_Air_Temperature_Setpoint/

**Screenshots**
![image](https://user-images.githubusercontent.com/14927790/106717791-75f5ac80-6600-11eb-862c-d716728dc7b9.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Edge
 - Version: 87.0.664.75 (64-Bit)

**Comment by shreyasnagare** [comment]
Thanks for the catch. I have added a fix on PR #103 which will be merged in later today if the changes are approved. You can test the deployed version [here](https://deploy-preview-103--brickschema.netlify.app/ontology/1.1/classes/Zone_Air_Temperature_Sensor/).

**Comment by GeorgFerdinandSchneider** [comment]
looks great, thanks for fixing!
