### ISSUE TITLE
SVG logo for Brick

### ISSUE THREAD

**Issue by jmertic** [BrickSchema/brick-website#161]
Hi! We would like to add Brick Schema to the LF Energy Landscape ( l.lfenergy.org ), but need a pure SVG of your logo; do you happen to have one? An EPS or AI version will also work. Thanks in advance!

**Comment by epaulson** [comment]
We unfortunately don't have a copy of the logo in a vector format (neither .svg nor .ai or even eps.) We've been meaning to make one but just haven't gotten to it yet.

**Comment by gtfierro** [comment]
@jbkoh can you double check if you have the original logo somewhere? I think I remember you adding it originally

**Comment by jbkoh** [comment]
@jmertic You may use this one: https://drive.google.com/file/d/1h3uLwjVolO5kHtjZf8NEeIy5DvykkGGG/view?usp=share_link

**Comment by jmertic** [comment]
Awesome - thank you! That version had an embedded PNG, but was able to do a trace and convert it to a pure SVG - see attached...

![brick](https://user-images.githubusercontent.com/296737/230436080-2b4a1139-11bf-4e2e-8444-3bacc8145766.svg)
