### ISSUE TITLE
High-level Concepts of Brick

### ISSUE THREAD

**Issue by shreyasnagare** [BrickSchema/brick-website#24]
Add a page that explains the core concepts of Brick briefly.

**Comment by jbkoh** [comment]
I think we can have a single page describing technical details where details can be collapsible. Please close this issue if you agree.

**Comment by gtfierro** [comment]
I'm on board with that, but I'd like to see the proposed copy first

**Comment by jbkoh** [comment]
Here's the current version: https://github.com/BrickSchema/brick-website/blob/addconceptpage/webpages/concepts/01.high-level.md

**Comment by gtfierro** [comment]
Can you submit this as a PR so its easier for me to provide comments?

**Comment by jbkoh** [comment]
I planned to add a bit more contents (especially about the class construction), but I will just PR first.

**Comment by jbkoh** [comment]
Related PR: https://github.com/BrickSchema/brick-website/pull/41
