### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by shreyasnagare** [BrickSchema/brick-website#25]
Add a page that explains how one can contribute to Brick.

**Comment by gtfierro** [comment]
I've created a `CONTRIBUTING.md` file for the Brick OWLDL repo: https://github.com/BrickSchema/brick-owl-dl/blob/master/CONTRIBUTING.md

What do you think @shreyasnagare @jbkoh?  I think we can adapt that to include directions for the website, and then copy the file over to the website repository and host it as a page, or just link to it from the website

**Comment by shreyasnagare** [comment]
> I've created a `CONTRIBUTING.md` file for the Brick OWLDL repo: https://github.com/BrickSchema/brick-owl-dl/blob/master/CONTRIBUTING.md
> 
> What do you think @shreyasnagare @jbkoh? I think we can adapt that to include directions for the website, and then copy the file over to the website repository and host it as a page, or just link to it from the website

Yeah, that makes sense. I read the new CONTRIBUTING.md and it seemed pretty straightforward. 

Apart from `contributing to the schema`, we should also highlight other ways to contribute like: `improving the documentation` (which would point to a different CONTRIBUTING.md). What do you think?

**Comment by gtfierro** [comment]
We derive the documentation from the ontology definition, so I think its appropriate to have the same CONTRIBUTING.md (which is how [GitHub recommends doing it](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors)). If we want to add other ways to contribute for resources in this repository, they should go into the same CONTRIBUTING.md file. The website repo should have its own CONTRIBUTING.md file that talks about how to set up the development environment, points people to the Brick repo for adjusting definitions, etc

**Comment by jbkoh** [comment]
Sorry I missed this notification. 

The current guideline is too generic. We need to be more specific about the contributions especially for expanding the Classes. Where should a contributor put the new Classes in the files? What information should be considered in adding them? For example, what are the rules to associate Tags with new Classes? I believe you remember one of the common questions we got was "where should I add this TagSet?". Like what Shreyas said, where to add definitions? We should be kind to the contributors, especially the contributors who may not have IT backgrounds in this project.

We need to migrate the repo to brickschema/brick as I proposed in another email. I just cloned the original Brick repo into brickschema group. Once the new version is ready to be released, we can migrate brick-owl-dl into the actual brick repo. We should remove "-owl-dl" from our official repo. It means that we need to change the links in the CONTRIBUTING.md, which will be shown on the website.

We need some testing framework. I wrote some heuristics for the previous code base, but the same logic may not apply to the new one. 

Minor comments: 
- I'd like to insert "release" here: "Make sure you are using the most recent ***release*** version of the Brick repository"

**Comment by jbkoh** [comment]
I think we need to have both CONTRIBUTING.md inside our Github repo as well as an HTML file generated from the md file.

**Comment by gtfierro** [comment]
Good suggestions! I'll add these to the CONTRIBUTING.md in the brick-owl-dl repository. When we migrate it over to the main Brick repo under this organization I'll be sure to fix all the links; we can then include the markdown file in the website repo so that it gets auto-converted to a webpage

**Comment by gtfierro** [comment]
Made changes: https://github.com/BrickSchema/brick-owl-dl/blob/master/CONTRIBUTING.md

Let me know what you think

**Comment by shreyasnagare** [comment]
Apart from "contributors", this page should be for the building managers as well (who want to propose changes to Brick), can I add that?

@jbkoh is there anything you want to add/modify in this file?

**Comment by gtfierro** [comment]
Can you clarify what you mean? Anyone who is contributing is a contributor

**Comment by shreyasnagare** [comment]
I know, right. It's just something we have on the _"Personas"_ google sheet. I believe that currently, we don't have enough content on the website that we need to categorize pages (based on persona). Once there are a lot of pages, we might have to suggest certain pages for each persona. Honestly, I don't think "contributor" is a persona (a contributor can be anyone) and we might want to rethink a little bit about the user types **once we have more content**.

**Comment by gtfierro** [comment]
The personas are just a tool to help determine the content, we don't need to explicitly refer to the personas anywhere
