### ISSUE TITLE
Website suggestions

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/brick-website#4]
Some things that jumped out to me. High-level feedback is this looks really nice!

- Sub headers should have anchor tags so we can link directly to them (e.g. https://brick.andrew.cmu.edu/start#Learning-Materials)

- When I click some of the headers, I get a blinking cursor (seen on Firefox). Is this intentional, or is there something funky with my browser?

- The documentation is nice functionally, but I think its a little too squeezed in the page. Could you make it wider? Also, the breadcrumbs on top are a little large, and ends up on multiple lines. Maybe making the font smaller and/or reducing the size?

- Stylistically, I'd prefer more spartan documentation. Something with higher contrast and fewer nested colors; Maybe a light grey/blue background and black text without a background?

- Can we have the apps page be a list/collection rather than a grid? I'd rather see a screenshot + a short text description + link line by line rather than only a small amount of information in a grid. Some of these have ugly-looking scrollbars on the side where the picture size exceeds the size of the grid

**Comment by gtfierro** [comment]
![image](https://user-images.githubusercontent.com/55434/60861389-273b2300-a1cf-11e9-9fde-d17727cb3418.png)

Example of the breadcrumbs being too large (bullet point 3)

**Comment by shreyasnagare** [comment]
> Some things that jumped out to me. High-level feedback is this looks really nice!

Thanks :)

> * Sub headers should have anchor tags so we can link directly to them (e.g. https://brick.andrew.cmu.edu/start#Learning-Materials)

Good call. [That](https://brick.andrew.cmu.edu/downloads/#Papers-and-Presentations) should work now.

> * When I click some of the headers, I get a blinking cursor (seen on Firefox). Is this intentional, or is there something funky with my browser?

I couldn't reproduce the blinking cursor. It probably has something to do with my user agent. I couldn't even see the breadcrumbs' scrollbars on MacOS (Chrome/Safari/Firefox).

> * The documentation is nice functionally, but I think its a little too squeezed in the page. Could you make it wider? Also, the breadcrumbs on top are a little large, and ends up on multiple lines. Maybe making the font smaller and/or reducing the size?
> * Stylistically, I'd prefer more spartan documentation. Something with higher contrast and fewer nested colors; Maybe a light grey/blue background and black text without a background?

@jbkoh had some suggestions related to the docs as well. There's a lot of scope for improvement, I guess. I think I should work on the styling after I hear from everyone (especially the UX people) as some suggestions might be overlapping and some contradicting. 

Regarding the breadcrumbs: I tried to make the breadcrumbs more compact when I first looked at [this](https://brick.andrew.cmu.edu/tagsets/Discharge_Water_Temperature_Setpoint) page. Although it looked bad, I was able to fit everything in the same line. Then I looked at the [deeper classes](https://brick.andrew.cmu.edu/tagsets/VAV_Occupied_Heating_Max_Discharge_Air_Flow_Setpoint) and realized that I had to make the breadcrumbs wrap anyway as it was something unavoidable (same goes for the word-break of the IRI). So, I decided not to keep them tightly packed. I did, however, keep the font size in the breadcrumbs lesser than almost all the other links on the website (docs/start/tagset/blog). I should make the page wider, I think. 👍 

> * Can we have the apps page be a list/collection rather than a grid? I'd rather see a screenshot + a short text description + link line by line rather than only a small amount of information in a grid. Some of these have ugly-looking scrollbars on the side where the picture size exceeds the size of the grid

That's a good idea. I was thinking something more like [Zulip Integrations](https://zulipchat.com/integrations). I made some changes to the [apps page](http://localhost:8080/apps). Check it out and let me know what you think.

**Comment by gtfierro** [comment]
Thanks for the quick turnaround! The blinking cursor is definitely a "me" thing, so don't worry about it.

If you want to try a slightly more refined Brick hierarchy, you can try the `Brick.ttl` file at https://github.com/BrickSchema/brick-owl-dl, which doesn't have as many long class names. I agree we'd need some other solution. We'll see how widening the page handles it.

I don't notice any obvious changes on the app page (I'll attach a screenshot). Pretty sure I've cleared my caches, so not sure what's up

**Comment by gtfierro** [comment]
![image](https://user-images.githubusercontent.com/55434/60924434-0bc72b00-a256-11e9-9e46-c5f9357d33c1.png)
