### ISSUE TITLE
Add webinar slides to the "Resources" page

### ISSUE THREAD

**Issue by shreyasnagare** [BrickSchema/brick-website#50]
@gtfierro I'm looking for the webinar (Why is the Brick Schema a Game Changer for Smart Buildings?) slides. Can we add it to the list of presentations?

**Comment by gtfierro** [comment]
We should definitely add it! Slides are available [on Google Slides](https://docs.google.com/presentation/d/1IF6WOhXDBZAJJ38vgNr5TxzqjdemxpSkIaLa-o0gGBo/edit?usp=sharing)

**Comment by jbkoh** [comment]
@gtfierro Are the slides on your UCB account?  (i.e., is it's under UCB's G-Suite?) I'm afraid the account may expire when you graduate, which happened on the original Brick folder under Bharath's UCLA account.

**Comment by gtfierro** [comment]
They are (and rest assured that I will handle the account contents before it expires), but we have the PDF of the presentation hosted on the Brick website

**Comment by jbkoh** [comment]
Ah, I got it. Thought we just posted the link. Thanks for the clarification.
