### ISSUE TITLE
Have the website re-build and re-deploy when there are commits to master

### ISSUE THREAD

**Issue by gtfierro** [BrickSchema/brick-website#51]
**Is your feature request related to a problem? Please describe.**
The website is out of date from the content in the repository. It would be nice if we had an automated process of deploying the website every time a commit is made to master. This motivates us to keep development to branches and forks, and reduces the effort in deploying the site.

**Describe the solution you'd like**
I'm not sure how the website is deployed now, but we can use commit hooks as the trigger for the build. Let me know if you'd like me to handle this and take over hosting of the site.

**Comment by shreyasnagare** [comment]
Automatic redeployments should work now (master branch only).

**Comment by gtfierro** [comment]
Awesome!
