### ISSUE TITLE
Display issue with ontology search feature

### ISSUE THREAD

**Issue by thisisbrians** [BrickSchema/brick-website#74]
The container holding the autocomplete suggestions when using the ontology search feature obscures the results:

![image](https://user-images.githubusercontent.com/1228122/78940883-34e24980-7a7c-11ea-8316-a8cd4d20b416.png)

I'm running Chrome 80.0.3987.149 (Official Build) (64-bit) on a MacBook Pro:
![image](https://user-images.githubusercontent.com/1228122/78940946-50e5eb00-7a7c-11ea-9f92-eef6546feb3b.png)

I could take a stab at this myself but wasn't sure how the interactions within the search results were intended.

**Comment by shreyasnagare** [comment]
@thisisbrians Thank you so much for letting us know about this. Unfortunately, I could not replicate the issue. 

Do any of the following builds seem to fix this for you?
1. [@4a3167a](https://5e8fb059feed980006e0b4a5--brickschema.netlify.com/ontology)
2. [@c21880f](https://5e8fb2aad9203c000671037e--brickschema.netlify.com/ontology)
